import { Document, DocumentChunk, Collection, SmartInsight, Conversation, Message, ExtractedResult } from '../types';

export const INITIAL_COLLECTIONS: Collection[] = [
  {
    id: 'col-1',
    name: 'Research Papers & AI Studies',
    description: 'Academic preprints, neural architecture research, and document AI benchmarks.',
    documentCount: 2,
    createdAt: '2026-08-10T10:00:00Z',
    color: 'bg-blue-500/20 text-blue-400 border-blue-500/30',
  },
  {
    id: 'col-2',
    name: 'Legal & Executive Contracts',
    description: 'Master service agreements, employment contracts, and NDA documents.',
    documentCount: 2,
    createdAt: '2026-08-11T14:30:00Z',
    color: 'bg-purple-500/20 text-purple-400 border-purple-500/30',
  },
  {
    id: 'col-3',
    name: 'Finance & Invoices',
    description: 'Vendor invoices, quarterly budgets, and infrastructure billing records.',
    documentCount: 1,
    createdAt: '2026-08-12T09:15:00Z',
    color: 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30',
  },
];

export const INITIAL_DOCUMENTS: Document[] = [
  {
    id: 'doc-tcet-paper',
    title: 'DocuSense AI: An AI-Powered Document Intelligence and Reasoning Platform',
    fileName: 'DocuSense_AI_TCET_Paper.pdf',
    fileSize: 2450000,
    fileType: 'pdf',
    pageCount: 11,
    chunkCount: 28,
    status: 'ready',
    uploadedAt: '2026-08-13T10:00:00Z',
    processedAt: '2026-08-13T10:02:15Z',
    collectionId: 'col-1',
    workspaceId: 'ws-default',
    author: 'Prathamesh Singh, Vedant Singh, Mihir Singh (TCET, Univ of Mumbai)',
    summaryQuick: [
      'Presents DocuSense AI, an intelligent document analysis and RAG system.',
      'Combines Optical Character Recognition (OCR), NLP, Vector Databases, and LLMs.',
      'Addresses key research gaps: complex layout parsing, OCR noise, retrieval latency, and model hallucination.',
      'Outlines 5-layer system architecture: Document Collection, Preprocessing, Information Extraction, Analysis, and Intelligent Retrieval.',
    ],
    summaryExec: {
      purpose: 'Systematic review and architectural framework for AI-powered document intelligence and contextual reasoning.',
      findings: [
        'Traditional keyword search fails for large-scale unstructured document repositories.',
        'Hybrid retrieval (semantic vector search + lexical matching) outperforms pure keyword retrieval.',
        'LayoutLMv3 and Donut models improve structural visual understanding.',
      ],
      numbers: ['15 high-quality research papers benchmarked', '5 core processing layers', '11 pages systematic study'],
      dates: ['Survey period: 2019 - 2025', 'Publication: 2024/2026'],
      risks: ['Model hallucination in clinical and legal settings', 'OCR error propagation in low-resolution scans'],
      recommendations: ['Adopt Explainable AI (XAI)', 'Integrate real-time document indexing', 'Deploy strict citation grounding'],
    },
    summaryTldr: 'A comprehensive research study proposing the DocuSense AI architecture that integrates OCR, RAG, and vector databases for enterprise document intelligence and zero-hallucination Q&A.',
  },
  {
    id: 'doc-contract-a',
    title: 'Executive Employment Agreement — Acme Corp & John Doe',
    fileName: 'Executive_Employment_Agreement_Acme.pdf',
    fileSize: 1120000,
    fileType: 'pdf',
    pageCount: 8,
    chunkCount: 16,
    status: 'ready',
    uploadedAt: '2026-08-11T11:20:00Z',
    processedAt: '2026-08-11T11:21:40Z',
    collectionId: 'col-2',
    workspaceId: 'ws-default',
    author: 'Acme Legal Team',
    summaryQuick: [
      'Employment agreement for Chief Technology Officer role at Acme Corp.',
      'Base salary set at $280,000 USD per annum with 20% annual performance bonus.',
      'Non-compete clause duration set to 12 months post-termination.',
      'Termination notice period requires 60 days written notice by either party.',
    ],
    summaryTldr: 'Executive agreement for CTO position outlining $280,000 base compensation, 12-month non-compete, and 60-day notice period.',
  },
  {
    id: 'doc-contract-b',
    title: 'Executive Employment Agreement — BetaTech & John Doe (Draft B)',
    fileName: 'Executive_Employment_Agreement_BetaTech.pdf',
    fileSize: 980000,
    fileType: 'pdf',
    pageCount: 7,
    chunkCount: 14,
    status: 'ready',
    uploadedAt: '2026-08-12T15:10:00Z',
    processedAt: '2026-08-12T15:11:05Z',
    collectionId: 'col-2',
    workspaceId: 'ws-default',
    author: 'BetaTech Legal Counsel',
    summaryQuick: [
      'Competing employment offer for VP of Engineering role at BetaTech Inc.',
      'Base compensation of $310,000 USD per annum with equity grant of 50,000 RSUs.',
      'Non-compete clause duration set to 24 months nationwide.',
      'Termination notice period requires 30 days written notice.',
    ],
    summaryTldr: 'BetaTech employment agreement offering $310k base salary + 50k RSUs with a stricter 24-month non-compete clause.',
  },
  {
    id: 'doc-invoice-101',
    title: 'Cloud Infrastructure Services Invoice — TechSolutions Corp #INV-2026-089',
    fileName: 'Invoice_INV_2026_089_TechSolutions.pdf',
    fileSize: 420000,
    fileType: 'pdf',
    pageCount: 2,
    chunkCount: 4,
    status: 'ready',
    uploadedAt: '2026-08-12T09:30:00Z',
    processedAt: '2026-08-12T09:30:22Z',
    collectionId: 'col-3',
    workspaceId: 'ws-default',
    author: 'TechSolutions Accounts Receivable',
    summaryQuick: [
      'Monthly billing invoice for Enterprise AWS Cluster & Vector DB Instance.',
      'Invoice Total Amount: $14,850.00 USD due by September 15, 2026.',
      'Includes GPU compute cluster time, pgvector cluster storage, and dedicated bandwidth.',
    ],
    summaryTldr: 'Monthly cloud infrastructure invoice totaling $14,850.00 due Sept 15, 2026.',
  },
];

export const INITIAL_CHUNKS: DocumentChunk[] = [
  // TCET Paper Chunks
  {
    id: 'chunk-tcet-1',
    documentId: 'doc-tcet-paper',
    documentTitle: 'DocuSense AI: An AI-Powered Document Intelligence Platform',
    pageNumber: 1,
    sectionTitle: 'ABSTRACT',
    chunkIndex: 1,
    text: 'DocuSense AI: An AI-Powered Document Intelligence and Reasoning Platform. Authors: Prathamesh Singh, Vedant Singh, Mihir Singh. Thakur College of Engineering and Technology (TCET). ABSTRACT: By integrating Optical Character Recognition, Natural Language Processing, Retrieval-Augmented Generation, vector databases, and Large Language Models, recent research has demonstrated significant improvements in document understanding, semantic search, question answering, and automated summarization.',
    tokenCount: 82,
  },
  {
    id: 'chunk-tcet-2',
    documentId: 'doc-tcet-paper',
    documentTitle: 'DocuSense AI: An AI-Powered Document Intelligence Platform',
    pageNumber: 3,
    sectionTitle: 'II. LITERATURE SURVEY - 2.4 Intelligent Document Retrieval',
    chunkIndex: 2,
    text: 'Retrieval-Augmented Generation (RAG) ensures that generated responses remain accurate, context-aware, and grounded in original document content. One of the foundational approaches in intelligent document retrieval is vector similarity search, which identifies relevant documents based on semantic similarity between user queries and document embeddings.',
    tokenCount: 74,
  },
  {
    id: 'chunk-tcet-3',
    documentId: 'doc-tcet-paper',
    documentTitle: 'DocuSense AI: An AI-Powered Document Intelligence Platform',
    pageNumber: 5,
    sectionTitle: 'III. SYSTEM OVERVIEW - 3.5 Intelligent Retrieval Engine',
    chunkIndex: 3,
    text: 'The intelligent retrieval module generates context-aware responses by retrieving relevant document sections based on user queries. It utilizes vector embeddings, semantic search, Retrieval-Augmented Generation (RAG), and Large Language Models to match user queries with relevant document content stored within vector databases.',
    tokenCount: 68,
  },
  {
    id: 'chunk-tcet-4',
    documentId: 'doc-tcet-paper',
    documentTitle: 'DocuSense AI: An AI-Powered Document Intelligence Platform',
    pageNumber: 9,
    sectionTitle: 'VI. RESEARCH GAPS AND CHALLENGES',
    chunkIndex: 4,
    text: 'Key research gaps in current document intelligence: 1. Reliance on domain-specific limited datasets. 2. Incomplete understanding of complex document layouts containing tables and multi-column structures. 3. Delayed retrieval of updated document information. 4. Privacy and ethical concerns in handling sensitive enterprise records. 5. Lack of model interpretability in black-box LLMs.',
    tokenCount: 78,
  },
  // Employment Contract A Chunks
  {
    id: 'chunk-ca-1',
    documentId: 'doc-contract-a',
    documentTitle: 'Executive Employment Agreement — Acme Corp',
    pageNumber: 2,
    sectionTitle: 'Section 3: Compensation and Bonus',
    chunkIndex: 1,
    text: '3.1 Base Compensation. Executive shall receive an annual base salary of $280,000 USD, payable in accordance with Company regular payroll practices. 3.2 Incentive Bonus. Executive is eligible for an annual performance bonus of up to 20% of base salary based on key performance metrics set by the Board.',
    tokenCount: 62,
  },
  {
    id: 'chunk-ca-2',
    documentId: 'doc-contract-a',
    documentTitle: 'Executive Employment Agreement — Acme Corp',
    pageNumber: 5,
    sectionTitle: 'Section 7: Restrictive Covenants & Non-Compete',
    chunkIndex: 2,
    text: '7.1 Non-Competition. For a period of twelve (12) months following termination of employment for any reason, Executive agrees not to engage in or advise any competing commercial software business operating within North America.',
    tokenCount: 45,
  },
  {
    id: 'chunk-ca-3',
    documentId: 'doc-contract-a',
    documentTitle: 'Executive Employment Agreement — Acme Corp',
    pageNumber: 7,
    sectionTitle: 'Section 10: Termination & Notice',
    chunkIndex: 3,
    text: '10.2 Termination Without Cause. Either party may terminate this Agreement without cause by providing sixty (60) calendar days prior written notice to the other party.',
    tokenCount: 34,
  },
  // Employment Contract B Chunks
  {
    id: 'chunk-cb-1',
    documentId: 'doc-contract-b',
    documentTitle: 'Executive Employment Agreement — BetaTech',
    pageNumber: 2,
    sectionTitle: 'Section 3: Compensation & Stock Options',
    chunkIndex: 1,
    text: '3.1 Salary. Base compensation shall be $310,000 USD annually. 3.2 Equity Grant. Subject to Board approval, Executive shall receive 50,000 Restricted Stock Units (RSUs) vesting over four (4) years with a one-year cliff.',
    tokenCount: 48,
  },
  {
    id: 'chunk-cb-2',
    documentId: 'doc-contract-b',
    documentTitle: 'Executive Employment Agreement — BetaTech',
    pageNumber: 5,
    sectionTitle: 'Section 8: Non-Compete Covenant',
    chunkIndex: 2,
    text: '8.1 Non-Compete. For a period of twenty-four (24) months post-termination, Executive shall not directly or indirectly engage in any enterprise developing cloud infrastructure solutions across the United States.',
    tokenCount: 41,
  },
  // Invoice Chunks
  {
    id: 'chunk-inv-1',
    documentId: 'doc-invoice-101',
    documentTitle: 'Cloud Infrastructure Services Invoice #INV-2026-089',
    pageNumber: 1,
    sectionTitle: 'Invoice Summary & Line Items',
    chunkIndex: 1,
    text: 'TechSolutions Corp Invoice #INV-2026-089. Invoice Date: August 12, 2026. Payment Due Date: September 15, 2026. Billed To: Acme Corp. Subtotal: $13,500.00. Tax (10%): $1,350.00. Total Amount Due: $14,850.00 USD.',
    tokenCount: 52,
  },
];

export const INITIAL_SMART_INSIGHTS: SmartInsight[] = [
  {
    id: 'ins-1',
    documentId: 'doc-invoice-101',
    documentTitle: 'Cloud Infrastructure Services Invoice #INV-2026-089',
    category: 'date',
    label: 'Payment Due Date',
    value: 'September 15, 2026',
    pageNumber: 1,
    contextSnippet: 'Payment Due Date: September 15, 2026. Billed To: Acme Corp.',
    severity: 'high',
  },
  {
    id: 'ins-2',
    documentId: 'doc-invoice-101',
    documentTitle: 'Cloud Infrastructure Services Invoice #INV-2026-089',
    category: 'financial',
    label: 'Total Outstanding Amount',
    value: '$14,850.00 USD',
    pageNumber: 1,
    contextSnippet: 'Subtotal: $13,500.00. Tax (10%): $1,350.00. Total Amount Due: $14,850.00 USD.',
    severity: 'high',
  },
  {
    id: 'ins-3',
    documentId: 'doc-contract-b',
    documentTitle: 'Executive Employment Agreement — BetaTech',
    category: 'risk',
    label: 'Extended 24-Month Non-Compete Risk',
    value: '24 Months Non-Compete',
    pageNumber: 5,
    contextSnippet: 'For a period of twenty-four (24) months post-termination, Executive shall not directly or indirectly engage...',
    severity: 'high',
  },
  {
    id: 'ins-4',
    documentId: 'doc-contract-a',
    documentTitle: 'Executive Employment Agreement — Acme Corp',
    category: 'financial',
    label: 'Base Compensation',
    value: '$280,000 USD / year',
    pageNumber: 2,
    contextSnippet: 'Executive shall receive an annual base salary of $280,000 USD, payable in accordance...',
    severity: 'low',
  },
  {
    id: 'ins-5',
    documentId: 'doc-tcet-paper',
    documentTitle: 'DocuSense AI: An AI-Powered Document Intelligence Platform',
    category: 'entity',
    label: 'Authors & Institution',
    value: 'Prathamesh Singh, Vedant Singh, Mihir Singh (TCET Mumbai)',
    pageNumber: 1,
    contextSnippet: 'Prathamesh Singh (28), Vedant Singh (31), Mihir Singh(22) - Thakur College of Engineering and Technology',
    severity: 'low',
  },
];
